<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Ant suite" duration-ms="21" started-at="2012-04-13T09:44:22Z" finished-at="2012-04-13T09:44:22Z">
    <groups>
    </groups>
    <test name="Ant test" duration-ms="21" started-at="2012-04-13T09:44:22Z" finished-at="2012-04-13T09:44:22Z">
      <class name="test.dummyTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test.dummyTest@13b8f864]" name="setUp" is-config="true" duration-ms="8" started-at="2012-04-13T09:44:22Z" finished-at="2012-04-13T09:44:22Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="decTest()[pri:0, instance:test.dummyTest@13b8f864]" name="decTest" duration-ms="1" started-at="2012-04-13T09:44:22Z" finished-at="2012-04-13T09:44:22Z">
        </test-method> <!-- decTest -->
        <test-method status="FAIL" signature="incTest()[pri:0, instance:test.dummyTest@13b8f864]" name="incTest" duration-ms="0" started-at="2012-04-13T09:44:22Z" finished-at="2012-04-13T09:44:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at test.dummyTest.incTest(dummyTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1022)
	at org.testng.TestNG.privateMain(TestNG.java:1330)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- incTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:test.dummyTest@13b8f864]" name="cleanUp" is-config="true" duration-ms="1" started-at="2012-04-13T09:44:22Z" finished-at="2012-04-13T09:44:22Z">
        </test-method> <!-- cleanUp -->
      </class> <!-- test.dummyTest -->
    </test> <!-- Ant test -->
  </suite> <!-- Ant suite -->
</testng-results>
